# Theme configuration
theme: jekyll-theme-cayman
title: 21 jours
description: Affiche la date à 21 jours
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/21-days/
baseUrl: https://c0zen.github.io/21-days/
gitHubUrl: https://github.com/C0ZEN/21-days

# Required when using import to import other sass files
sass:
  sass_dir: ./assets/css